# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from viitorvoice.grpc_server.proto import backend_provider_pb2 as viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2


class BackendProviderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/tts.backend.v1.BackendProviderService/Health',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.HealthRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.HealthResponse.FromString,
                )
        self.GetCapabilities = channel.unary_unary(
                '/tts.backend.v1.BackendProviderService/GetCapabilities',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.CapabilitiesResponse.FromString,
                )
        self.PreparePrompt = channel.unary_unary(
                '/tts.backend.v1.BackendProviderService/PreparePrompt',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.PreparePromptRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.PreparePromptResponse.FromString,
                )
        self.Synthesize = channel.unary_unary(
                '/tts.backend.v1.BackendProviderService/Synthesize',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeResponse.FromString,
                )
        self.SynthesizeStream = channel.unary_stream(
                '/tts.backend.v1.BackendProviderService/SynthesizeStream',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeStreamEvent.FromString,
                )


class BackendProviderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreparePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackendProviderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.HealthRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.HealthResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'PreparePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.PreparePrompt,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.PreparePromptRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.PreparePromptResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeResponse.SerializeToString,
            ),
            'SynthesizeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeStreamEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.backend.v1.BackendProviderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BackendProviderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.backend.v1.BackendProviderService/Health',
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.HealthRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.backend.v1.BackendProviderService/GetCapabilities',
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.GetCapabilitiesRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.CapabilitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PreparePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.backend.v1.BackendProviderService/PreparePrompt',
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.PreparePromptRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.PreparePromptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.backend.v1.BackendProviderService/Synthesize',
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SynthesizeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tts.backend.v1.BackendProviderService/SynthesizeStream',
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_backend__provider__pb2.SynthesizeStreamEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
