# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: viitorvoice/grpc_server/proto/viitorvoice_decoder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from viitorvoice.grpc_server.proto import viitorvoice_common_pb2 as viitorvoice_dot_grpc__server_dot_proto_dot_viitorvoice__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7viitorvoice/grpc_server/proto/viitorvoice_decoder.proto\x12\x18viitorvoice.inference.v2\x1a\x36viitorvoice/grpc_server/proto/viitorvoice_common.proto\"\xe9\x01\n\x12\x44\x65\x63odeAudioRequest\x12\x39\n\x07\x63ontext\x18\x01 \x01(\x0b\x32(.viitorvoice.inference.v2.RequestContext\x12>\n\x0f\x61udio_codebooks\x18\x02 \x03(\x0b\x32%.viitorvoice.inference.v2.Int64Tensor\x12\x1a\n\x12postprocess_output\x18\x03 \x01(\x08\x12<\n\routput_format\x18\x04 \x01(\x0e\x32%.viitorvoice.inference.v2.AudioFormat\"\x87\x01\n\x13\x44\x65\x63odeAudioResponse\x12:\n\x07\x63ontext\x18\x01 \x01(\x0b\x32).viitorvoice.inference.v2.ResponseContext\x12\x34\n\x05\x61udio\x18\x02 \x01(\x0b\x32%.viitorvoice.inference.v2.AudioResult2\xe4\x01\n\x19ViiTorVoiceDecoderService\x12[\n\x06Health\x12\'.viitorvoice.inference.v2.HealthRequest\x1a(.viitorvoice.inference.v2.HealthResponse\x12j\n\x0b\x44\x65\x63odeAudio\x12,.viitorvoice.inference.v2.DecodeAudioRequest\x1a-.viitorvoice.inference.v2.DecodeAudioResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'viitorvoice.grpc_server.proto.viitorvoice_decoder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DECODEAUDIOREQUEST._serialized_start=142
  _DECODEAUDIOREQUEST._serialized_end=375
  _DECODEAUDIORESPONSE._serialized_start=378
  _DECODEAUDIORESPONSE._serialized_end=513
  _VIITORVOICEDECODERSERVICE._serialized_start=516
  _VIITORVOICEDECODERSERVICE._serialized_end=744
# @@protoc_insertion_point(module_scope)
