# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from viitorvoice.grpc_server.proto import viitorvoice_common_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2
from viitorvoice.grpc_server.proto import viitorvoice_decoder_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__decoder__pb2


class ViiTorVoiceDecoderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceDecoderService/Health',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
                )
        self.DecodeAudio = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceDecoderService/DecodeAudio',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__decoder__pb2.DecodeAudioRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__decoder__pb2.DecodeAudioResponse.FromString,
                )


class ViiTorVoiceDecoderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecodeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViiTorVoiceDecoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.SerializeToString,
            ),
            'DecodeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.DecodeAudio,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__decoder__pb2.DecodeAudioRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__decoder__pb2.DecodeAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viitorvoice.inference.v2.ViiTorVoiceDecoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ViiTorVoiceDecoderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceDecoderService/Health',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DecodeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceDecoderService/DecodeAudio',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__decoder__pb2.DecodeAudioRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__decoder__pb2.DecodeAudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
