# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from viitorvoice.grpc_server.proto import viitorvoice_common_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2
from viitorvoice.grpc_server.proto import viitorvoice_llm_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2


class ViiTorVoiceLLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceLLMService/Health',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
                )
        self.Generate = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceLLMService/Generate',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateResponse.FromString,
                )
        self.GenerateFromSemantic = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceLLMService/GenerateFromSemantic',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateFromSemanticRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateFromSemanticResponse.FromString,
                )
        self.GenerateLocalEdit = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceLLMService/GenerateLocalEdit',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateLocalEditRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateLocalEditResponse.FromString,
                )


class ViiTorVoiceLLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFromSemantic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateLocalEdit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViiTorVoiceLLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateResponse.SerializeToString,
            ),
            'GenerateFromSemantic': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFromSemantic,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateFromSemanticRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateFromSemanticResponse.SerializeToString,
            ),
            'GenerateLocalEdit': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLocalEdit,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateLocalEditRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateLocalEditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viitorvoice.inference.v2.ViiTorVoiceLLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ViiTorVoiceLLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceLLMService/Health',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceLLMService/Generate',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateFromSemantic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceLLMService/GenerateFromSemantic',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateFromSemanticRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateFromSemanticResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateLocalEdit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceLLMService/GenerateLocalEdit',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateLocalEditRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__llm__pb2.LLMGenerateLocalEditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
