# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: viitorvoice/grpc_server/proto/viitorvoice_encoder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from viitorvoice.grpc_server.proto import viitorvoice_common_pb2 as viitorvoice_dot_grpc__server_dot_proto_dot_viitorvoice__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7viitorvoice/grpc_server/proto/viitorvoice_encoder.proto\x12\x18viitorvoice.inference.v2\x1a\x36viitorvoice/grpc_server/proto/viitorvoice_common.proto\"\xef\x01\n\x12\x45ncodeAudioRequest\x12\x39\n\x07\x63ontext\x18\x01 \x01(\x0b\x32(.viitorvoice.inference.v2.RequestContext\x12\x33\n\x05\x61udio\x18\x02 \x01(\x0b\x32$.viitorvoice.inference.v2.AudioInput\x12\x19\n\x11preprocess_prompt\x18\x03 \x01(\x08\x12\x14\n\x0creturn_audio\x18\x04 \x01(\x08\x12 \n\x13\x63\x61n_trim_long_audio\x18\x05 \x01(\x08H\x00\x88\x01\x01\x42\x16\n\x14_can_trim_long_audio\"\xe8\x01\n\x13\x45ncodeAudioResponse\x12:\n\x07\x63ontext\x18\x01 \x01(\x0b\x32).viitorvoice.inference.v2.ResponseContext\x12=\n\x0e\x61udio_codebook\x18\x02 \x01(\x0b\x32%.viitorvoice.inference.v2.Int64Tensor\x12\x13\n\x0bsample_rate\x18\x03 \x01(\r\x12\x41\n\x12preprocessed_audio\x18\x04 \x01(\x0b\x32%.viitorvoice.inference.v2.AudioResult2\xe4\x01\n\x19ViiTorVoiceEncoderService\x12[\n\x06Health\x12\'.viitorvoice.inference.v2.HealthRequest\x1a(.viitorvoice.inference.v2.HealthResponse\x12j\n\x0b\x45ncodeAudio\x12,.viitorvoice.inference.v2.EncodeAudioRequest\x1a-.viitorvoice.inference.v2.EncodeAudioResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'viitorvoice.grpc_server.proto.viitorvoice_encoder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENCODEAUDIOREQUEST._serialized_start=142
  _ENCODEAUDIOREQUEST._serialized_end=381
  _ENCODEAUDIORESPONSE._serialized_start=384
  _ENCODEAUDIORESPONSE._serialized_end=616
  _VIITORVOICEENCODERSERVICE._serialized_start=619
  _VIITORVOICEENCODERSERVICE._serialized_end=847
# @@protoc_insertion_point(module_scope)
