# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from viitorvoice.grpc_server.proto import viitorvoice_common_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2
from viitorvoice.grpc_server.proto import viitorvoice_encoder_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2


class ViiTorVoiceEncoderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceEncoderService/Health',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
                )
        self.EncodeAudio = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceEncoderService/EncodeAudio',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioResponse.FromString,
                )


class ViiTorVoiceEncoderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViiTorVoiceEncoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.SerializeToString,
            ),
            'EncodeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeAudio,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viitorvoice.inference.v2.ViiTorVoiceEncoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ViiTorVoiceEncoderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceEncoderService/Health',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EncodeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceEncoderService/EncodeAudio',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
