# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from viitorvoice.grpc_server.proto import viitorvoice_common_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2
from viitorvoice.grpc_server.proto import viitorvoice_encoder_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2
from viitorvoice.grpc_server.proto import viitorvoice_orchestrator_pb2 as viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2


class ViiTorVoiceOrchestratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/Health',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
                )
        self.EncodeAudio = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/EncodeAudio',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioResponse.FromString,
                )
        self.Synthesize = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/Synthesize',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SynthesizeResponse.FromString,
                )
        self.SemanticToWav = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/SemanticToWav',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SemanticToWavRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SemanticToWavResponse.FromString,
                )
        self.AlignForEdit = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/AlignForEdit',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.AlignForEditRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.AlignForEditResponse.FromString,
                )
        self.LocalEdit = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/LocalEdit',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.LocalEditRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.LocalEditResponse.FromString,
                )
        self.TextLocalEdit = channel.unary_unary(
                '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/TextLocalEdit',
                request_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.TextLocalEditRequest.SerializeToString,
                response_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.TextLocalEditResponse.FromString,
                )


class ViiTorVoiceOrchestratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticToWav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlignForEdit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalEdit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextLocalEdit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViiTorVoiceOrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.SerializeToString,
            ),
            'EncodeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeAudio,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SynthesizeRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SynthesizeResponse.SerializeToString,
            ),
            'SemanticToWav': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticToWav,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SemanticToWavRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SemanticToWavResponse.SerializeToString,
            ),
            'AlignForEdit': grpc.unary_unary_rpc_method_handler(
                    servicer.AlignForEdit,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.AlignForEditRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.AlignForEditResponse.SerializeToString,
            ),
            'LocalEdit': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalEdit,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.LocalEditRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.LocalEditResponse.SerializeToString,
            ),
            'TextLocalEdit': grpc.unary_unary_rpc_method_handler(
                    servicer.TextLocalEdit,
                    request_deserializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.TextLocalEditRequest.FromString,
                    response_serializer=viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.TextLocalEditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viitorvoice.inference.v2.ViiTorVoiceOrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ViiTorVoiceOrchestratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/Health',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__common__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EncodeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/EncodeAudio',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__encoder__pb2.EncodeAudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/Synthesize',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SynthesizeRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SynthesizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SemanticToWav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/SemanticToWav',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SemanticToWavRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.SemanticToWavResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlignForEdit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/AlignForEdit',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.AlignForEditRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.AlignForEditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LocalEdit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/LocalEdit',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.LocalEditRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.LocalEditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TextLocalEdit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viitorvoice.inference.v2.ViiTorVoiceOrchestratorService/TextLocalEdit',
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.TextLocalEditRequest.SerializeToString,
            viitorvoice__grpc__server_dot_proto_dot_viitorvoice__orchestrator__pb2.TextLocalEditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
